version:0.2

phases:
  install:
    runtime-versions:
      nodejs: 8.17
    commands:
      -cd noteworx-react-mongodb
      -npm install -g npm@3
      -npm install -g mongodb@3.6
      -npm install

  build:
    commands:
      -npn run build

  post_build:
    commands:
      -npm run lint
      -npm run serve:api &
      -npm run serve:dev
  
  artifacts:
    files:
      -noteworx-react-mongodb/Client/public/**/*
      -noteworx-react-mongodb/Server/**/*

  cache:
    paths:
      -node_modules/
