version: '3'
services:
  mongodb:
    image: mongo:3.6
    restart: never
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: never
    ports:
      - 9000:9000
    depends_on:
      - mongodb

volumes:
  mongodb-data: 
